import type { Metadata } from "next";
import { Shantell_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from '../app/components/providers';
const andika = Shantell_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400",
});


// Good font
// Inria_Sans
// Tilt_Neon
// livvic
// Andika
// Removed unused livvic font initialization to fix unused variable error and missing required properties.
// const chococooky = localFont({
//   src: "../../public/font/chococooky.ttf",
//   variable: "--font-chococooky",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Html converter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${andika.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
